import Foundation
import FocusCore
var count = 0
func check(_ value: @autoclosure () -> Bool, _ name: String) { guard value() else { fatalError("FAIL: \(name)") }; count += 1; print("PASS: \(name)") }
var tap = DoubleTap()
check(!tap.update(pressed: true, clean: true, time: 0), "first down")
check(!tap.update(pressed: false, clean: true, time: 0.05), "single tap")
_ = tap.update(pressed: true, clean: true, time: 0.15)
check(tap.update(pressed: false, clean: true, time: 0.2), "double tap")
_ = tap.update(pressed: true, clean: true, time: 1)
check(!tap.update(pressed: false, clean: true, time: 2), "long control rejected")
_ = tap.update(pressed: true, clean: true, time: 3)
_ = tap.update(pressed: false, clean: true, time: 3.1)
_ = tap.update(pressed: true, clean: false, time: 3.2)
check(!tap.update(pressed: false, clean: true, time: 3.3), "chord rejected")
_ = tap.update(pressed: true, clean: true, time: 4)
_ = tap.update(pressed: false, clean: true, time: 4.1)
_ = tap.update(pressed: true, clean: true, time: 5)
check(!tap.update(pressed: false, clean: true, time: 5.1), "expired double tap")
tap.cancel()
_ = tap.update(pressed: true, clean: true, time: 10)
_ = tap.update(pressed: true, clean: false, time: 10.05)
_ = tap.update(pressed: true, clean: true, time: 10.1)
check(!tap.update(pressed: false, clean: true, time: 10.15), "releasing Option before Control does not count as tap")
_ = tap.update(pressed: true, clean: true, time: 10.2)
check(!tap.update(pressed: false, clean: true, time: 10.25), "chord release cannot pair with next Control")
var hold = Hold()
hold.press(0); hold.press(1)
check(!hold.tick(2.9), "2.9 seconds preserves canvas")
check(hold.tick(3), "3 seconds fires")
check(!hold.tick(4), "fires once")
hold.cancel(); hold.press(5); hold.cancel(); hold.press(7)
check(!hold.tick(8), "release resets elapsed time")
var history = History<Int>()
history.add(1); history.add(2); history.undo()
check(history.items == [1], "undo")
history.redo(); check(history.items == [1,2], "redo")
history.undo(); history.add(3); check(history.future.isEmpty, "new stroke drops redo")
history.clear(); check(history.items.isEmpty && history.future.isEmpty, "new canvas clears history")
check(localPoint(CGPoint(x: -900, y: 50), frame: CGRect(x: -1000, y: -100, width: 1000, height: 800)) == CGPoint(x: 100, y: 150), "negative screen coordinates in logical points")
var gate = EscapeCapture()
check(!gate.keyDown(lessonActive:false), "idle Escape passes through with decorative effects")
check(gate.keyDown(lessonActive:true), "lesson owns Escape")
check(gate.keyDown(lessonActive:false), "repeat after ending remains consumed")
check(gate.keyUp(), "matching release consumed")
check(!gate.keyDown(lessonActive:false), "next Escape passes through after release")
_ = gate.keyDown(lessonActive:true); gate.reset()
check(!gate.keyDown(lessonActive:false), "pause cancels Escape ownership")
var customHold=Hold()
customHold.press(0,duration:1.5)
check(!customHold.tick(1.49) && customHold.tick(1.5), "custom 1.5 second hold")
customHold.cancel(); customHold.press(0,duration:5)
customHold.press(1,duration:0.5)
check(!customHold.tick(4.9) && customHold.tick(5), "duration captured at initial key-down")
customHold.cancel(); customHold.press(0,duration:0)
check(!customHold.tick(0.49) && customHold.tick(0.5), "zero duration clamped to 0.5 seconds")
customHold.cancel(); customHold.press(0,duration:100)
check(!customHold.tick(9.9) && customHold.tick(10), "duration capped at 10 seconds")
let original = Shortcut(key:2,modifiers:Shortcut.control | Shortcut.option)
check(original.validationError()==nil, "default shortcut valid")
check(original.validationError(other:original) != nil, "duplicate shortcuts rejected")
check(Shortcut(key:3,modifiers:Shortcut.command | Shortcut.shift).validationError(other:original)==nil, "recorded modifiers and key accepted")
check(Shortcut(key:53,modifiers:Shortcut.control).validationError() != nil, "Escape cannot replace a shortcut")
check(Shortcut(key:3,modifiers:0).validationError() != nil, "unmodified typing rejected")
check(Shortcut(key:3,modifiers:Shortcut.shift).validationError() != nil, "Shift-only typing rejected")
check(Shortcut(key:12,modifiers:Shortcut.command).validationError() != nil, "Command Q protected")
var entrance=SpotlightEntrance()
entrance.begin(10)
check(entrance.sample(10).scale == 1.65 && entrance.sample(10).opacity == 0, "focus animation begins wide and transparent")
let middle=entrance.sample(10.125)
check(middle.scale > 1 && middle.scale < 1.65 && middle.opacity > 0 && middle.opacity < 1, "focus animation smoothly narrows and dims")
check(entrance.sample(10.25).scale == 1 && !entrance.sample(10.25).animating, "focus animation settles at configured radius")
check(entrance.sample(10.01,reducedMotion:true).scale == 1 && !entrance.sample(10.01,reducedMotion:true).animating, "reduce motion skips transition")
entrance.reset(); check(entrance.sample(11).scale == 1, "ending spotlight clears animation")
print("\(count) checks passed")
