import Foundation
import FocusCore
var count = 0
func check(_ value: @autoclosure () -> Bool, _ name: String) { guard value() else { fatalError("FAIL: \(name)") }; count += 1; print("PASS: \(name)") }
var tap = DoubleTap()
check(!tap.update(pressed: true, clean: true, time: 0), "first down")
check(!tap.update(pressed: false, clean: true, time: 0.05), "single tap")
_ = tap.update(pressed: true, clean: true, time: 0.15)
check(tap.update(pressed: false, clean: true, time: 0.2), "double tap")
_ = tap.update(pressed: true, clean: true, time: 1)
check(!tap.update(pressed: false, clean: true, time: 2), "long control rejected")
_ = tap.update(pressed: true, clean: true, time: 3)
_ = tap.update(pressed: false, clean: true, time: 3.1)
_ = tap.update(pressed: true, clean: false, time: 3.2)
check(!tap.update(pressed: false, clean: true, time: 3.3), "chord rejected")
_ = tap.update(pressed: true, clean: true, time: 4)
_ = tap.update(pressed: false, clean: true, time: 4.1)
_ = tap.update(pressed: true, clean: true, time: 5)
check(!tap.update(pressed: false, clean: true, time: 5.1), "expired double tap")
tap.cancel()
_ = tap.update(pressed: true, clean: true, time: 10)
_ = tap.update(pressed: true, clean: false, time: 10.05)
_ = tap.update(pressed: true, clean: true, time: 10.1)
check(!tap.update(pressed: false, clean: true, time: 10.15), "releasing Option before Control does not count as tap")
_ = tap.update(pressed: true, clean: true, time: 10.2)
check(!tap.update(pressed: false, clean: true, time: 10.25), "chord release cannot pair with next Control")
var hold = Hold()
hold.press(0); hold.press(1)
check(!hold.tick(2.9), "2.9 seconds preserves canvas")
check(hold.tick(3), "3 seconds fires")
check(!hold.tick(4), "fires once")
hold.cancel(); hold.press(5); hold.cancel(); hold.press(7)
check(!hold.tick(8), "release resets elapsed time")
var history = History<Int>()
history.add(1); history.add(2); history.undo()
check(history.items == [1], "undo")
history.redo(); check(history.items == [1,2], "redo")
history.undo(); history.add(3); check(history.future.isEmpty, "new stroke drops redo")
history.clear(); check(history.items.isEmpty && history.future.isEmpty, "new canvas clears history")
check(localPoint(CGPoint(x: -900, y: 50), frame: CGRect(x: -1000, y: -100, width: 1000, height: 800)) == CGPoint(x: 100, y: 150), "negative screen coordinates in logical points")
print("\(count) checks passed")
