using TeachingFocus.Core;
int checks = 0;
void Check(bool condition, string name) { if (!condition) throw new Exception("FAIL: " + name); checks++; Console.WriteLine("PASS: " + name); }
var tap = new DoubleControl();
Check(!tap.Change(true, true, 0) && !tap.Change(false, true, .05), "single Control does not trigger");
tap.Change(true, true, .15); Check(tap.Change(false, true, .2), "double Control triggers");
tap.Change(true, true, 1); Check(!tap.Change(false, true, 2), "long Control rejected");
tap.Change(true, true, 3); tap.Change(true, false, 3.05); tap.Change(true, true, 3.1);
Check(!tap.Change(false, true, 3.15), "modifier chord release is not a tap");
tap.Change(true, true, 3.2); Check(!tap.Change(false, true, 3.25), "next Control does not pair with chord");
tap.Reset(); tap.Change(true, true, 4); tap.Change(false, true, 4.05); tap.Change(true, true, 5);
Check(!tap.Change(false, true, 5.05), "expired double tap rejected");
var hold = new EscapeHold();
Check(!hold.KeyDown(false, 0), "idle Escape passes through even when decorative halo is enabled");
Check(hold.KeyDown(true, 0), "lesson Escape is consumed");
hold.KeyDown(true, 2); Check(!hold.Tick(2.9), "autorepeat does not change hold start; no early exit");
Check(hold.Tick(3), "hold completes at three seconds");
hold.EndLesson(); Check(hold.KeyDown(false, 3.1), "post-exit repeat is consumed until release");
Check(!hold.Tick(4), "hold fires once");
Check(hold.KeyUp() && !hold.KeyDown(false, 5), "release restores normal Escape");
hold.KeyDown(true, 6); hold.KeyUp(); hold.KeyDown(true, 8);
Check(!hold.Tick(9), "short holds do not accumulate");
var state = new SessionState();
int token = state.BeginCapture()!.Value;
Check(!state.FinishCapture(token, false) && !state.LessonActive, "failed capture cannot freeze");
token = state.BeginCapture()!.Value; state.Pause();
Check(!state.FinishCapture(token, true) && !state.Frozen && state.Paused, "pause invalidates pending capture");
state.ToggleSpotlight(); Check(!state.Spotlight, "paused spotlight cannot activate");
state.Resume(); state.ToggleSpotlight(); Check(state.LessonActive, "resume permits lesson");
state.EndLesson(); Check(!state.LessonActive, "ending lesson clears active state");
token = state.BeginCapture()!.Value; Check(state.FinishCapture(token, true) && state.Frozen, "successful capture freezes");
state.Pause(); Check(!state.Frozen && !state.LessonActive, "pause clears frozen state");
var history = new History<int>(); history.Add(1); history.Add(2); history.Undo();
Check(history.Items.SequenceEqual([1]), "undo"); history.Redo(); Check(history.Items.SequenceEqual([1, 2]), "redo");
history.Undo(); history.Add(3); history.Redo(); Check(history.Items.SequenceEqual([1, 3]), "new stroke discards redo");
history.Clear(); Check(history.Items.Count == 0, "new canvas clears history");
Check(Coordinates.Local(-900, 50, -1000, -100, 1.5, 1.5) == (100 / 1.5, 100), "negative monitor origin at 150 percent DPI");
Check(Coordinates.Local(2100, 300, 1920, 0, 2, 2) == (90, 150), "second screen at 200 percent DPI");
Check(new Shortcut(Modifiers.Control | Modifiers.Alt, 0x44).ValidationError() == null, "recorded Ctrl Alt D accepted");
Check(new Shortcut(Modifiers.None, 0x41).ValidationError() != null, "plain letters rejected");
Check(new Shortcut(Modifiers.Windows, 0x44).ValidationError() != null, "Windows shortcuts rejected");
Check(new Shortcut(Modifiers.Alt, 0x73).ValidationError() != null, "Alt F4 rejected");
Check(new Shortcut(Modifiers.Control, 0x7B).ValidationError() != null, "F12 reserved");
Check(new Shortcut(Modifiers.Control, 0x70).ValidationError() == null, "Ctrl F1 accepted");
Console.WriteLine($"{checks} checks passed");
